### ISSUE TITLE
Depth sorting on QuadtreeSprite children

### ISSUE THREAD

**Issue by BenLeffler** [justpinegames/QuadtreeSprite-Extension#1]
Hi there,

Firstly - let me just say, awesome work. This will definitely come in handy for future Starling isometric work.

I have however come across an issue where depth sorting is a little screwy on QuadtreeSprite children.

Say - for example - if you add a whole bunch of quads in order from 0 to n-1, the order of depth is not retained when rendering. (See attached images)

I tried adding in a sort function on the "visibleObjects" vector in the refresh() function based on the index of the display object in the class _children vector, however I have found that this causes a performance overhead when depth sorting at this point in the logic, especially when you have a high draw count on the screen at any particular point and/or you're frequently updating the visibleViewPort object.

This is your baby, so over to you!

Cheers,
Ben Leffler.
![withoutSorting](https://f.cloud.github.com/assets/3096583/268866/23e5ce12-8f61-11e2-8981-6f6673483cb9.jpg)
![withSorting](https://f.cloud.github.com/assets/3096583/268867/23eea974-8f61-11e2-860e-0c28ce7346fb.jpg)

**Comment by tpodhraski** [comment]
How did you find an index for the objects? If you used indexOf() thats O(n) and if called from a sort function it will be slow.

I've forgot to mention that the sort of insertion is not maintained. I'll look into how to solve this. There are some problems however.

For now, if you are sorting just for the Y as in the picture, listen to Event.CHANGE and use sort as you would on Starling Sprite.

**Comment by BenLeffler** [comment]
Yeah, I was running a sort based on the index of the display object in the _children vector, which proved an overhead. For now, I'll do as you suggested until a faster solution becomes apparent.

Once again - cheers for the nice work.

**Comment by tpodhraski** [comment]
I've added a way to specify that the container maintains order, using a second constructor parameter:
QuadtreeSprite(worldSpace:Rectangle, maintainOrder:Boolean = false)

However, the implementation is still slower than when not maintaining the order. It's comparable to sorting on change event.
